trigger:
  branches:
    include:
      - main

pool:
  name: MyLinuxPool   # <<< your self-hosted pool name

steps:
  - checkout: self
    clean: true

  - script: |
        echo "Deployment Started..."
        chmod +x /home/aiwms/public_html/ai-tools-backend/cicdtest/deploy.sh
        bash /home/aiwms/public_html/ai-tools-backend/cicdtest/deploy.sh
    displayName: "Deploy FRONTEND"